# Generated by Django 2.2.3 on 2019-12-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20191227_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.TextField(default='2019-12-31'),
        ),
    ]
